language: node_js
node_js: "10.15"
cache: yarn

stages:
  - name: test
  - name: notify_start
    if: tag is present
  - name: deploy
    if: tag is present
  - name: notify
    if: tag is present

jobs:
  include:
    - stage: test
      env:
        - NODE_ENV=test

    - stage: notify_start
      script: deploy/notify-start.sh
      install: skip

    - stage: notify
      script: deploy/notify.sh
      install: skip

    - stage: deploy
      name: Laser Focus World
      script: deploy/index.js laserfocusworld aerilon
      install: skip

    - stage: deploy
      name: Military & Aerospace Electronics
      script: deploy/index.js militaryaerospace aerilon
      install: skip

    - stage: deploy
      name: Utility Products
      script: deploy/index.js utilityproducts aerilon
      install: skip

    - stage: deploy
      name: Vision Systems Design
      script: deploy/index.js vision-systems aerilon
      install: skip
